name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('push-{0}', github.sha) || format('push-{0}', github.ref) }}

jobs:
  pr:
    uses: ./.github/workflows/build.yml
    secrets: inherit
