name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  pr:
    uses: ./.github/workflows/build.yml
    secrets: inherit
